version: 1.0.{build}
image: Visual Studio 2022
environment:
  nodejs_version: "18"
  GITHUB_TOKEN:
    secure: ${GITHUB_TOKEN}

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

build_script:
  - yarn build

on_success:
  - ps: |
      git config --global credential.helper store
      Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_TOKEN):x-oauth-basic@github.com`n"
      git config --global user.email "appveyor@example.com"
      git config --global user.name "AppVeyor CI"
      cd dist
      git init
      git add .
      git commit -m "Auto-deploy [skip ci]"
      git push --force --quiet "https://$($env:GITHUB_TOKEN)@github.com/Vladislav-Proshchenkov/Gnome-Killer.git" master:gh-pages
      git ls-remote --heads "https://github.com/Vladislav-Proshchenkov/Gnome-Killer.git" gh-pages